### ISSUE TITLE
Suggestion for -p flag. 

### ISSUE THREAD

**Issue by Druanae** [Sweets/nougat#2]
Add the ability to include a month or year along with the -p flag to only purge that flag.  
I suggest also using _all_ instead of just the -p flag alone to prevent accidental purging.

**Comment by Sweets** [comment]
-p has been "remapped" to the `clean` method, so that it will remove any links that go to nowhere (e.g. removing a file)

-S is the "new" -p. Rather than it removing anything, it's a file selection argument, which will output all files matching a specific string. This was done so that users could process the files on their own.

For example, removing all images is done by `rm $(nougat -S "*-*-*+*:*:*")`
